version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Listing source files"
      - ls -la

  build:
    commands:
      - echo "Build phase"

artifacts:
  files:
    - appspec.yml
    - server.js
    - package.json
    - package-lock.json
    - scripts/**/*
    - lambda/**/*
