version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Build started"

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
